apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: podinfo
  namespace: wego-system
spec:
  checkout:
    branch: dev
    gitRepositoryRef:
      name: podinfo-config
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update image'
  interval: 30s
