apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: podinfo
  namespace: wego-system
spec:
  sourceRef:
    kind: GitRepository
    name: podinfo-config-webapp
  git:
    checkout:
      ref:
        branch: dev
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '[ci skip] update image'
  interval: 30s
