apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: wego-system
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 6.0.x
